[![Build WsaPatch.dll](https://github.com/ALANXD1177/Halland/actions/workflows/build.yml/badge.svg?branch=main&event=workflow_dispatch)](https://github.com/ALANXD1177/Halland/actions/workflows/build.yml)
